name: sigma-delta
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - moviepy
  - numpy=1.11
  - Pillow
  - pip
  - pytest
  - python=2
  - scipy=0.18
  - scikit-learn
  - tabulate
  - Theano=0.8
  - pip:
    - -e git+http://github.com/QUVA-Lab/artemis.git@0.1.0#egg=artemis
    - -e git+http://github.com/petered/plato@0.1.1#egg=plato
    - -e git+http://github.com/QUVA-Lab/artemis.git#egg=artemis
    - -e git+http://github.com/petered/plato#egg=plato
